baseURL = "https://rickkoch.github.com"
languageCode = "en-us"
title = "RickKoch"
theme="archie"
copyright = "Â© rick"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "hello world!"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rickKoch"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/itsRickKoch/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/rickKoch/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
